package com.example.tarotadivination

var words = arrayListOf(
    "algoritmo",
    "compilar",
    "servidor",
    "programar",
    "base de datos",
    "depurar",
    "interfaz",
    "desarrollar",
    "código fuente",
    "implementar",
    "hardware",
    "configurar",
    "software",
    "diseñar",
    "red neuronal",
    "entrenar",
    "inteligencia artificial",
    "analizar",
    "sistema operativo",
    "actualizar",
    "navegador",
    "explorar",
    "repositorio",
    "clonar",
    "kernel",
    "optimizar",
    "protocolo",
    "autenticar",
    "firewall",
    "proteger",
    "enrutador",
    "conectar",
    "virtualización",
    "simular",
    "token",
    "validar",
    "blockchain",
    "descentralizar",
    "malware",
    "detectar",
    "phishing",
    "prevenir",
    "API",
    "integrar",
    "backend",
    "construir",
    "frontend",
    "renderizar",
    "base de datos",
    "consultar",
    "script",
    "ejecutar",
    "variable",
    "declarar",
    "constante",
    "asignar",
    "bucle",
    "iterar",
    "condición",
    "evaluar",
    "objeto",
    "instanciar",
    "clase",
    "heredar",
    "método",
    "invocar",
    "parámetro",
    "pasar",
    "retorno",
    "devolver",
    "excepción",
    "manejar",
    "error",
    "capturar",
    "depuración",
    "rastrear",
    "compilador",
    "traducir",
    "intérprete",
    "interpretar",
    "lenguaje de programación",
    "codificar",
    "biblioteca",
    "importar",
    "framework",
    "estructurar",
    "entorno de desarrollo",
    "configurar",
    "versión",
    "controlar",
    "commit",
    "registrar",
    "push",
    "subir",
    "pull",
    "descargar",
    "merge",
    "fusionar",
    "rama",
    "documentación",
    "comentario",
    "anotar",
    "licencia",
    "foro",
    "discutir",
    "tutorial",
    "aprender",
    "curso",
    "enseñar",
    "certificación",
    "desarrollar",
    "proyecto",
    "planificar",
    "equipo",
    "coordinar",
    "reunión",
    "revisión",
    "feedback",
    "implementar",
    "actualización",
    "desplegar",
    "mantenimiento",
    "soporte",
    "usuario",
    "interactuar",
    "experiencia",
    "interfaz",
    "diseñar",
    "testear",
    "rendimiento",
    "optimizar",
    "seguridad",
    "vulnerabilidad",
    "parche",
    "autenticación",
    "autorización",
    "acceso",
    "datos",
    "análisis",
    "monitoreo",
    "log",
    "registrar",
    "evento",
    "métrica",
    "dashboard",
    "auditoría",
    "innovación",
    "investigación",
    "retroalimentación"
)


var excellentLuck = arrayListOf("Sean todas tus instalaciones exitosas de hoy hacia el futuro",
    "Enhorabuena! No tendrás que preocuparte por troyanos o peor, el Succ nunca más",
    "Nunca más volverán los duendes a enredar tus cables. ¡Vida libre de desenredos!",
    "Hágase la voluntad de la red! Disfruta de tu futuro periodo surcando sin miedo a anuncios invasivos o escuchas indeseadas",
    "¡Disfruta de tu suerte en 32bits! Nada podrá pararte")
var realNiceLuck = arrayListOf("¡Por un periodo sin anuncios de aquello que acabas de pensar, tu buena suerte has de disfrutar!",
    "El oráculo ha hablado: Sean las IAs esquivas a tu arte. Sean las IAs contaminadas por tu acción. Sea tu huella irremplazable y fuerte",
    "Nada ni nadie puede imitarte. Todo marcha, todo fluye. Asalta, piratea y actúa sin temor",
    "Grandes descubrimientos esperan. Con esta suerte que veo, tal vez llegues a encontrar los ansiados artefactos perdidos de la red",
    "Veo chips, bits y transistores. Montajes rápidos, componentes libres de polvo y portátiles que no se cuelgan. ¡Celebremos!")
var wellLuck = arrayListOf("Piénsalo, al menos el Succ no te está persiguiendo",
    "Navegue usted con parche! y nieguese el estado de Israel",
    "¿No es acaso estar aquí un signo de buena suerte en si mismo? ¡Regocíjate technokasero!",
    "No todo el mundo tiene tu suerte. La voluntad del oraculo te llenara de torrents palomiteros en buena calidad",
    "Bit a bit, forjas camino con aquellos que te siguen y a quienes admiras, disfruta el camino")
var regularLuck = arrayListOf("Cuidate del Succ, no quieras ser su prioridad...",
    "Ni un dia sin sol ni un pc sin ralentizar. Miralo por el lado bueno, al menos tienes gente alrededor que lo puede traer de vuelta a la vida",
    "¿Imaginas hallar los artefactos perdidos de la red? Yo tampoco, al menos no sin compañia",
    "Dura es la lucha compartida. Avanza con tus comaradas a un mundo libre de noticias falsas",
    "Una vida normal es una suerte normal. No hace falta tener seguidores o destacar, ni todos tus datos están a salvo. Y no hay que estresarse demasiado por ello")
var badLuck = arrayListOf("No te molestes... El Succ ha ganado... Tiene tus datos, tus fotos, TODO... Sabe dónde vives y va a por ti!",
    "Apaga el teléfono... Nos escuchan!",
    "Algo me dice que debes pasar el antivirus a tu pc... ¿No querrás que esos bichines sigan minando cryptos para otros?",
    "Evita GPT! Ninguna solución que te ofrezca puede ser buena. Esta suerte solo se soluciona liberándonos de las maquinas",
    "Hay reliquias perdidas en la red que otros podrán atribuirse meritos. Disfruta de ayudar y verlas aparecer. A veces la mejor forma de contrarrestar esta suerte es actuar en comunidad")

